version: "3.9"

networks:
  chegah-network:
    driver: bridge

services:
  backend:
    build: ./be
    volumes:
     - ./be/static:/app/staticfiles
     - ./be/media:/app/media
    expose:
      - 8010
    ports:
      - "8020:8010"
    networks:
      - chegah-network
    # env_file:
    #   - .env.production 

  frontend:
    build: ./fe
    ports:
      - 3020:3010
    networks:
      - chegah-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped


